import type { CatalogueEdition, Category, Product, StoreSettings } from './types';

function img(id: string, file: string, alt: string, position: number) {
  return { id, url: `/images/products/${file}`, alt_text: alt, position };
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    slug: 'sea-mist-chanderi-silk-saree',
    sku: 'SB-CHK-014',
    name: 'Sea Mist Chanderi Silk Saree',
    tagline: 'with Real Silver Zari',
    category_id: 'cat-heritage',
    category_slug: 'heritage-sarees',
    category_name: 'Heritage Sarees & Drapes',
    price: 9800,
    mrp: 12900,
    unit: 'piece',
    stock_qty: 14,
    stock_status: 'in_stock',
    is_new: true,
    is_bestseller: true,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-001a', 'sea-mist.svg', 'Sea Mist Chanderi Silk Saree drape', 0),
      img('img-001b', 'royal-indigo.svg', 'Silver zari border detail', 1),
      img('img-001c', 'pastel-mint-organza.svg', 'Weave close-up', 2),
    ],
    yarn_label: '100% Pure Chanderi Silk',
    fabric_composition: '100% Pure Chanderi Silk Warp & Weft',
    weave: 'Authentic Traditional Handloom with Real Silver Mukaish Zari',
    dimensions: '6.5 Meters (includes unstitched running blouse 0.8m)',
    care: 'Dry clean only. Store wrapped in breathable muslin cloth.',
    certifications: 'Silk Mark Certified #SKM-992 • Craftmark Handloom Certified',
    origin: 'Madhya Pradesh Looms',
    artisan_quote:
      'Each meter of this gossamer weave takes 14 hours of continuous rhythm on the wooden pit-loom. The sea-mist hue is steeped from natural indigo and marigold water bath to achieve that calm ocean dawn shimmer.',
    artisan_name: 'Ustad Riazuddin & Family',
    artisan_place: 'Pranpur, Chanderi',
    description:
      'A featherlight Chanderi silk saree in a sea-mist hue, woven with real silver zari on traditional pit-looms of Pranpur. Master artisan drapes harmonizing deep ocean hues, handspun threads, and delicate golden shimmer.',
  },
  {
    id: 'prod-002',
    slug: 'royal-indigo-jamdani-weave',
    sku: 'SB-JAM-008',
    name: 'Royal Indigo Jamdani Weave',
    tagline: 'Hand-spun Jamdani Motifs',
    category_id: 'cat-heritage',
    category_slug: 'heritage-sarees',
    category_name: 'Heritage Sarees & Drapes',
    price: 16200,
    mrp: 19800,
    unit: 'piece',
    stock_qty: 3,
    stock_status: 'low',
    is_new: false,
    is_bestseller: true,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-002a', 'royal-indigo.svg', 'Royal Indigo Jamdani Weave drape', 0),
      img('img-002b', 'indigo-dabu.svg', 'Jamdani motif detail', 1),
    ],
    yarn_label: 'Fine Cotton-Silk Jamdani',
    fabric_composition: 'Hand-spun Cotton warp, Mulberry Silk weft',
    weave: 'Discontinuous-weft Jamdani, hand-inserted motifs',
    dimensions: '6.3 Meters (includes unstitched running blouse 0.8m)',
    care: 'Dry clean only. Air out after festive wear.',
    certifications: 'Craftmark Handloom Certified',
    origin: 'West Bengal Looms',
    artisan_quote:
      'Jamdani cannot be hurried. Each motif is counted thread by thread, and a single saree passes through my hands for twenty days before it is ready for the world.',
    artisan_name: 'Birendra Basak & Family',
    artisan_place: 'Shantipur, West Bengal',
    description:
      'A royal indigo Jamdani woven with hand-inserted geometric motifs in mulberry silk weft. Deep ocean hues meet heirloom geometry in this festive drape.',
  },
  {
    id: 'prod-003',
    slug: 'raw-tussar-temple-border',
    sku: 'SB-TUS-108',
    name: 'Raw Tussar Temple Border Saree',
    tagline: 'Wild Silk, Temple Weave',
    category_id: 'cat-heritage',
    category_slug: 'heritage-sarees',
    category_name: 'Heritage Sarees & Drapes',
    price: 11500,
    mrp: 13900,
    unit: 'piece',
    stock_qty: 9,
    stock_status: 'in_stock',
    is_new: false,
    is_bestseller: false,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-003a', 'raw-tussar.svg', 'Raw Tussar Temple Border saree drape', 0),
      img('img-003b', 'vintage-gold-katan.svg', 'Temple border detail', 1),
    ],
    yarn_label: 'Raw Wild Tussar Silk',
    fabric_composition: '100% Raw Tussar Silk, hand-reeled',
    weave: 'Traditional temple-border handloom with contrast zari',
    dimensions: '6.4 Meters (includes unstitched running blouse 0.8m)',
    care: 'Dry clean only. Avoid direct sunlight for long hours.',
    certifications: 'Silk Mark Certified #SKM-118',
    origin: 'Chhattisgarh & Odisha Looms',
    artisan_quote:
      'Tussar is wild silk — it keeps the texture of the forest. We do not tame it; we let the slubs speak and frame them with a temple border worthy of a shrine.',
    artisan_name: 'Padma Looms Collective',
    artisan_place: 'Raigarh, Chhattisgarh',
    description:
      'Raw tussar silk saree with a classic temple border, hand-reeled wild silk with a naturally rich slubbed texture and contrast zari edging.',
  },
  {
    id: 'prod-004',
    slug: 'pastel-mint-organza-zari',
    sku: 'SB-ORG-019',
    name: 'Pastel Mint Organza with Zari',
    tagline: 'Sheer Festive Organza',
    category_id: 'cat-silk-yardage',
    category_slug: 'silk-yardage',
    category_name: 'Pure Silk Yardage',
    price: 8400,
    mrp: 9900,
    unit: 'piece',
    stock_qty: 18,
    stock_status: 'in_stock',
    is_new: true,
    is_bestseller: false,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-004a', 'pastel-mint-organza.svg', 'Pastel Mint Organza saree drape', 0),
      img('img-004b', 'sea-mist.svg', 'Zari shimmer detail', 1),
    ],
    yarn_label: 'Silk Organza with Zari',
    fabric_composition: 'Mulberry Silk organza with fine gold zari',
    weave: 'Sheer plain-weave organza, hand-finished edges',
    dimensions: '6.3 Meters (includes unstitched running blouse 0.8m)',
    care: 'Dry clean only. Handle zari with soft hands.',
    certifications: 'Silk Mark Certified #SKM-204',
    origin: 'Varanasi Looms',
    artisan_quote:
      'Organza is glass made of silk. One wrong pull and the whole meter is lost — so we weave it slowly, in the cool of the morning.',
    artisan_name: 'Ansari Weaving House',
    artisan_place: 'Varanasi, Uttar Pradesh',
    description:
      'A pastel mint silk organza saree kissed with fine gold zari — sheer, crisp, and quietly festive for daytime celebrations.',
  },
  {
    id: 'prod-005',
    slug: 'desert-sand-pure-linen-saree',
    sku: 'SB-LIN-042',
    name: 'Desert Sand Pure Linen Saree',
    tagline: 'European Flax, Indian Loom',
    category_id: 'cat-linen',
    category_slug: 'linen-blends',
    category_name: 'Linen & Blends',
    price: 6900,
    mrp: 8200,
    unit: 'piece',
    stock_qty: 45,
    stock_status: 'in_stock',
    is_new: true,
    is_bestseller: false,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-005a', 'desert-sand-linen.svg', 'Desert Sand Pure Linen saree drape', 0),
      img('img-005b', 'raw-tussar.svg', 'Linen texture detail', 1),
    ],
    yarn_label: '100% Pure Linen',
    fabric_composition: '100% European flax linen, garment-washed',
    weave: 'Handloom plain weave, stone-washed softness',
    dimensions: '6.3 Meters (includes unstitched running blouse 0.8m)',
    care: 'Machine wash gentle or hand wash. Gets softer with every wash.',
    certifications: 'European Flax Certified Linen',
    origin: 'Bengal Linen Looms',
    artisan_quote:
      'Linen is honest cloth. It wrinkles where you laughed and softens where you lived. We weave it loose and wash it kind so it arrives already feeling like yours.',
    artisan_name: 'Maa Tara Handlooms',
    artisan_place: 'Fulia, West Bengal',
    description:
      'A desert-sand pure linen saree — breathable, earthy, and garment-washed for softness. Everyday luxury woven from European flax on Bengal looms.',
  },
  {
    id: 'prod-006',
    slug: 'vintage-gold-katan-silk',
    sku: 'SB-BAN-102',
    name: 'Vintage Gold Katan Silk',
    tagline: 'Banarasi Bridal Heirloom',
    category_id: 'cat-bridal',
    category_slug: 'bridal-katan',
    category_name: 'Bridal Weaves & Katan',
    price: 24500,
    mrp: 28900,
    unit: 'piece',
    stock_qty: 0,
    stock_status: 'made_to_order',
    is_new: false,
    is_bestseller: true,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-006a', 'vintage-gold-katan.svg', 'Vintage Gold Katan Silk drape', 0),
      img('img-006b', 'royal-indigo.svg', 'Katan buttis detail', 1),
    ],
    yarn_label: 'Pure Katan Silk, Tested Zari',
    fabric_composition: 'Pure mulberry katan silk with tested gold zari',
    weave: 'Kadhuwa Banarasi handloom, hand-cut buttis',
    dimensions: '6.5 Meters (includes unstitched running blouse 1m)',
    care: 'Dry clean only. Store flat with acid-free tissue.',
    certifications: 'Silk Mark Certified #SKM-311 • GI Tagged Banarasi',
    origin: 'Varanasi Looms',
    artisan_quote:
      'A bridal katan is woven once in a weaver’s lifetime with full heart. The gold you see is my grandfather’s pattern, redrawn by my daughter.',
    artisan_name: 'Haji Ahmed & Sons',
    artisan_place: 'Varanasi, Uttar Pradesh',
    description:
      'A vintage-gold Banarasi katan silk woven with kadhuwa buttis in tested gold zari. Made to order on the looms of Varanasi — an heirloom for the bridal trousseau.',
  },
  {
    id: 'prod-007',
    slug: 'indigo-dabu-print-fabric',
    sku: 'SB-COT-092',
    name: 'Indigo Dabu Print Fabric',
    tagline: 'Hand Block, Bagru Craft',
    category_id: 'cat-cotton',
    category_slug: 'artisanal-cotton',
    category_name: 'Artisanal Cotton & Dabu',
    price: 650,
    mrp: 780,
    unit: 'meter',
    stock_qty: 120,
    stock_status: 'in_stock',
    is_new: false,
    is_bestseller: false,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-007a', 'indigo-dabu.svg', 'Indigo Dabu Print Fabric stack', 0),
      img('img-007b', 'desert-sand-linen.svg', 'Block print detail', 1),
    ],
    yarn_label: '100% Handloom Cotton',
    fabric_composition: '100% combed cotton cambric, azo-free dyes',
    weave: 'Hand block printed with natural indigo, dabu mud resist',
    dimensions: 'Sold per meter • Width 44 inches',
    care: 'First wash in cold salt water. Wash darks separately.',
    certifications: 'Craftmark Handloom Certified',
    origin: 'Bagru Ateliers, Rajasthan',
    artisan_quote:
      'Dabu is mud, lime, and patience. We print the resist by hand, dye in the indigo vat seven times, and wash in the river. No two meters are ever the same.',
    artisan_name: 'Chhipa Family Atelier',
    artisan_place: 'Bagru, Rajasthan',
    description:
      'Authentic Bagru dabu hand-block printed cotton in deep indigo. Sold per meter for kurtas, drapes, and soft furnishings — wholesale friendly.',
  },
  {
    id: 'prod-008',
    slug: 'ivory-sheer-tissue-dupatta',
    sku: 'SB-DUP-031',
    name: 'Ivory Sheer Tissue Dupatta',
    tagline: 'Moonlight Tissue Weave',
    category_id: 'cat-dupatta',
    category_slug: 'dupattas-stoles',
    category_name: 'Dupattas & Stoles',
    price: 4200,
    mrp: 5200,
    unit: 'piece',
    stock_qty: 22,
    stock_status: 'in_stock',
    is_new: true,
    is_bestseller: false,
    is_visible: true,
    whatsapp_enabled: true,
    images: [
      img('img-008a', 'ivory-tissue.svg', 'Ivory Sheer Tissue Dupatta', 0),
      img('img-008b', 'pastel-mint-organza.svg', 'Tissue sheen detail', 1),
    ],
    yarn_label: 'Silk Tissue, Ivory',
    fabric_composition: 'Mulberry silk tissue with fine metallic weft',
    weave: 'Sheer tissue plain weave, hand-rolled hems',
    dimensions: '2.5 Meters × 1 Meter',
    care: 'Dry clean only. Keep away from sharp jewellery.',
    certifications: 'Silk Mark Certified #SKM-150',
    origin: 'Chanderi Looms',
    artisan_quote:
      'Tissue catches light like water at dawn. We weave it thin enough to read through, then hem it by hand so it floats instead of falling.',
    artisan_name: 'Riazuddin & Family',
    artisan_place: 'Pranpur, Chanderi',
    description:
      'An ivory sheer tissue dupatta with a moonlight sheen — the perfect layer over festive ensembles, hand-rolled and featherlight.',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-heritage',
    slug: 'heritage-sarees',
    name: 'Heritage Sarees & Drapes',
    description: 'Heirloom handloom sarees from India’s master weaving clusters.',
    image_url: '/images/products/sea-mist.svg',
    position: 1,
    is_visible: true,
    product_count: 3,
  },
  {
    id: 'cat-silk-yardage',
    slug: 'silk-yardage',
    name: 'Pure Silk Yardage',
    description: 'Silk yardage for bespoke tailoring and bridal couture.',
    image_url: '/images/products/pastel-mint-organza.svg',
    position: 2,
    is_visible: true,
    product_count: 1,
  },
  {
    id: 'cat-cotton',
    slug: 'artisanal-cotton',
    name: 'Artisanal Cotton & Dabu',
    description: 'Hand block prints, dabu resist, and artisanal cottons.',
    image_url: '/images/products/indigo-dabu.svg',
    position: 3,
    is_visible: true,
    product_count: 1,
  },
  {
    id: 'cat-linen',
    slug: 'linen-blends',
    name: 'Linen & Blends',
    description: 'Breathable linens and blends for everyday luxury.',
    image_url: '/images/products/desert-sand-linen.svg',
    position: 4,
    is_visible: true,
    product_count: 1,
  },
  {
    id: 'cat-dupatta',
    slug: 'dupattas-stoles',
    name: 'Dupattas & Stoles',
    description: 'Sheer tissues, embroidered dupattas and stoles.',
    image_url: '/images/products/ivory-tissue.svg',
    position: 5,
    is_visible: true,
    product_count: 1,
  },
  {
    id: 'cat-bridal',
    slug: 'bridal-katan',
    name: 'Bridal Weaves & Katan',
    description: 'Banarasi katan and bridal heirloom weaves.',
    image_url: '/images/products/vintage-gold-katan.svg',
    position: 6,
    is_visible: true,
    product_count: 1,
  },
];

export const MOCK_SETTINGS: StoreSettings = {
  business_name: 'Sea Birds Luxury Textiles',
  tagline: 'Heritage handloom, ocean calm',
  address: 'Sea Birds Atelier, 14 Marina Row, Fort, Mumbai 400001',
  phone: '+91 98201 44520',
  email: 'concierge@seabirdstextiles.in',
  whatsapp_number: '+919820144520',
  advisor_name: 'Master Loom Concierge',
  whatsapp_default_message: 'Hello Sea Birds, I would like to know more about your weaves.',
  ateliers: [
    { id: 'at-1', name: 'Chanderi Weaving Hub', location: 'Pranpur, Madhya Pradesh' },
    { id: 'at-2', name: 'Bagru Print Atelier', location: 'Bagru, Rajasthan' },
    { id: 'at-3', name: 'Varanasi Katan Looms', location: 'Varanasi, Uttar Pradesh' },
  ],
};

export const MOCK_EDITIONS: CatalogueEdition[] = [
  {
    id: 'ed-001',
    title: 'Autumn/Festive Handloom Vol. IV',
    volume: 'Vol. IV • 2026',
    description: '142 master weaves with yarn specs, wholesale tiers and artisan stories.',
    scope: 'master',
    file_url: '/catalogues/autumn-festive-handloom-vol-iv.pdf',
    file_size_mb: 14,
    cover_image_url: '/images/products/sea-mist.svg',
    created_at: '2026-09-15',
  },
  {
    id: 'ed-002',
    title: 'Bridal Katan & Tissue Edit',
    volume: 'Bridal 2026',
    description: 'Curated bridal katan, tissue and zari weaves with bulk tiers.',
    scope: 'category',
    file_url: '/catalogues/bridal-katan-tissue-edit.pdf',
    file_size_mb: 8,
    cover_image_url: '/images/products/vintage-gold-katan.svg',
    created_at: '2026-08-02',
  },
  {
    id: 'ed-003',
    title: 'Everyday Cottons & Dabu',
    volume: 'Wholesale 2026',
    description: 'Wholesale-friendly cottons, dabu prints and linens by the meter.',
    scope: 'category',
    file_url: '/catalogues/everyday-cottons-dabu.pdf',
    file_size_mb: 6,
    cover_image_url: '/images/products/indigo-dabu.svg',
    created_at: '2026-06-20',
  },
];
